/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormDetail_Penjualan.java
 *
 * Created on Jun 25, 2010, 10:04:18 PM
 */

package ClientApplicationi.form;

import com.mysql.jdbc.Statement;
import ClientApplication.FormClient;
import ClientApplication.model.TableModelDetail_Penjualan;
import Database.Entity.Detail_Penjualan;
import Database.Service.Detail_PenjualanService;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Madridista
 */
public class FormDetail_Penjualan extends javax.swing.JFrame {

    private TableModelDetail_Penjualan tableModelDetail_Penjualan = new TableModelDetail_Penjualan();
    private Detail_PenjualanService detail_PenjualanService;
    /** Creates new form FormDetail_Penjualan */
    public FormDetail_Penjualan(Detail_PenjualanService detail_PenjualanService) {
        this.detail_PenjualanService = detail_PenjualanService;
        try{
            tableModelDetail_Penjualan.setData(this.detail_PenjualanService.getDetail_Penjualan());
        }catch(RemoteException exception){
            exception.printStackTrace();
        }
        initComponents();

        tableDetail_Penjualan.setModel(tableModelDetail_Penjualan);
        tableDetail_Penjualan.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                int row = tableDetail_Penjualan.getSelectedRow();
                if(row != -1){
                    Detail_Penjualan detail_Penjualan = tableModelDetail_Penjualan.get(row);
                    Id_Penjualan.setSelectedItem(detail_Penjualan.getId_Penjualan().toString());
                    Id_Barang.setSelectedItem(detail_Penjualan.getId_Barang().toString());
                    Jml.setText(""+detail_Penjualan.getJml());
                }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableDetail_Penjualan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Jml = new javax.swing.JTextField();
        Id_Penjualan = new javax.swing.JComboBox();
        Id_Barang = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        Insert = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableDetail_Penjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableDetail_Penjualan);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DETAIL_PENJUALAN"));

        jLabel1.setText("Id_Penjualan");

        jLabel2.setText("Id_Barang");

        jLabel3.setText("Jumlah");

        Id_Penjualan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[Pilih]" }));
        Id_Penjualan.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                Id_PenjualanPopupMenuWillBecomeVisible(evt);
            }
        });

        Id_Barang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[Pilih]" }));
        Id_Barang.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                Id_BarangPopupMenuWillBecomeVisible(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Id_Penjualan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Id_Barang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jml, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Id_Penjualan)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Id_Barang)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jml, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        Insert.setText("INSERT");
        Insert.setPreferredSize(new java.awt.Dimension(90, 30));
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });
        jPanel2.add(Insert);

        Update.setText("UPDATE");
        Update.setPreferredSize(new java.awt.Dimension(90, 30));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel2.add(Update);

        Delete.setText("DELETE");
        Delete.setPreferredSize(new java.awt.Dimension(90, 30));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel2.add(Delete);

        Refresh.setText("REFRESH");
        Refresh.setPreferredSize(new java.awt.Dimension(90, 30));
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel2.add(Refresh);

        Exit.setText("EXIT");
        Exit.setPreferredSize(new java.awt.Dimension(90, 30));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel2.add(Exit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(255, 255, 255))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        // TODO add your handling code here:
 if(Id_Penjualan.getSelectedItem().equals("[Pilih]")||Id_Barang.getSelectedItem().equals("[Pilih]")||Jml.getText().equalsIgnoreCase("")){
       JOptionPane.showMessageDialog(null, "Data Yang Anda Inputkan Belum Lengkap");

   }
   else{

        String x = (String) Id_Penjualan.getSelectedItem();
        long y = Long.parseLong(x);
        String a = (String) Id_Barang.getSelectedItem();
        long b = Long.parseLong(a);
        String c = Jml.getText();
        int d = Integer.parseInt(c);

        try{

           Detail_Penjualan detail_Penjualan = new Detail_Penjualan();
           detail_Penjualan.setId_Penjualan(y);
           detail_Penjualan.setId_Barang(b);
           detail_Penjualan.setJml(d);

           Detail_Penjualan detail_Penjualan1= detail_PenjualanService.insertDetail_Penjualan(detail_Penjualan);
           tableModelDetail_Penjualan.insert(detail_Penjualan1);
        }catch(RemoteException exception){
            exception.printStackTrace();
        }
   }
    }//GEN-LAST:event_InsertActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
 if(Id_Penjualan.getSelectedItem().equals("[Pilih]")||Id_Barang.getSelectedItem().equals("[Pilih]")||Jml.getText().equalsIgnoreCase("")){
       JOptionPane.showMessageDialog(null, "Data Yang Anda Inputkan Belum Lengkap");

   }
   else{
        try{

            int row = tableDetail_Penjualan.getSelectedRow();
            if(row == -1){
                return;
            }
        String x = (String) Id_Penjualan.getSelectedItem();
        long y = Long.parseLong(x);
        String a = (String) Id_Barang.getSelectedItem();
        long b = Long.parseLong(a);
        String c = Jml.getText();
        int d = Integer.parseInt(c);
           Detail_Penjualan detail_Penjualan = tableModelDetail_Penjualan.get(row);
           detail_Penjualan.setId_Penjualan(y);
           detail_Penjualan.setId_Barang(b);
           detail_Penjualan.setJml(d);

           detail_PenjualanService.updateDetail_Penjualan(detail_Penjualan);
           tableModelDetail_Penjualan.update(row, detail_Penjualan);
        }catch(RemoteException exception){
            exception.printStackTrace();
        }
   }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        try{

            int row = tableDetail_Penjualan.getSelectedRow();
            if(row == -1){
                return;
            }
        Long Id_Penjualan = tableModelDetail_Penjualan.get(row).getId_Penjualan();
        Long Id_Barang = tableModelDetail_Penjualan.get(row).getId_Barang();

           detail_PenjualanService.deleteDetail_Penjualan(Id_Barang, Id_Penjualan);
           tableModelDetail_Penjualan.delete(row);
        }catch(RemoteException exception){
            exception.printStackTrace();
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        try{
           List<Detail_Penjualan> list = detail_PenjualanService.getDetail_Penjualan();
           tableModelDetail_Penjualan.setData(list);
        }catch(RemoteException exception){
            exception.printStackTrace();
        }
    }//GEN-LAST:event_RefreshActionPerformed

    private void Id_PenjualanPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_Id_PenjualanPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        // hapus seluruh data combobox
	Id_Penjualan.removeAllItems();

	// load data dari database ke combobox
	Statement statement = null;
	ResultSet resultSet = null;
	try {
	    statement = (Statement) databasehelper.getConnection().createStatement();
	    resultSet = statement.executeQuery("select Id_Penjualan from Penjualan");
	    while (resultSet.next()) {
		String kategori = resultSet.getString("Id_Penjualan");
		Id_Penjualan.addItem(kategori);
	    }
	} catch (SQLException ex) {
	} finally {
	    try {
		if (resultSet != null) {
		    resultSet.close();
		}
	    } catch (SQLException ex) {
	    }
	    try {
		if (statement != null) {
		    statement.close();
		}
	    } catch (SQLException ex) {
	    }
	}
    }//GEN-LAST:event_Id_PenjualanPopupMenuWillBecomeVisible

    private void Id_BarangPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_Id_BarangPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        // hapus seluruh data combobox
	Id_Barang.removeAllItems();

	// load data dari database ke combobox
	Statement statement = null;
	ResultSet resultSet = null;
	try {
	    statement = (Statement) databasehelper.getConnection().createStatement();
	    resultSet = statement.executeQuery("select Id_Barang from Barang");
	    while (resultSet.next()) {
		String kategori = resultSet.getString("Id_Barang");
		Id_Barang.addItem(kategori);
	    }
	} catch (SQLException ex) {
	} finally {
	    try {
		if (resultSet != null) {
		    resultSet.close();
		}
	    } catch (SQLException ex) {
	    }
	    try {
		if (statement != null) {
		    statement.close();
		}
	    } catch (SQLException ex) {
	    }
	}
    }//GEN-LAST:event_Id_BarangPopupMenuWillBecomeVisible

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
          FormClient formClient = new FormClient();
            formClient.setVisible(true);
        } catch (RemoteException ex) {
            Logger.getLogger(FormDetail_Penjualan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(FormDetail_Penjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ExitActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Exit;
    private javax.swing.JComboBox Id_Barang;
    private javax.swing.JComboBox Id_Penjualan;
    private javax.swing.JButton Insert;
    private javax.swing.JTextField Jml;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableDetail_Penjualan;
    // End of variables declaration//GEN-END:variables

}
